name: ethos_penalps_env

channels:
  - conda-forge

dependencies:
  - python >=3.10
  - cloudpickle
  - dataclasses-json
  - datapane
  - datetimerange
  - graphviz
  - jsonpickle
  - matplotlib
  - networkx
  - numpy >1.23.5
  - openpyxl
  - pandas
  - pdf2image
  - pint
  - pip >=21.3
  - plotly
  - proplot
  - python-graphviz
  - setuptools  # required by proplot for pkg_resources
  - seaborn
  - sqlalchemy <2.0
  - strenum
  - svglib
  - typeguard
  - workalendar
  - xlsxwriter
  - tectonic

  # Development / testing
  - pandas-stubs
  - pytest >7.0
  - pytest-xdist
  - types-datetimerange
  - ruff
  - nbval
  - nbconvert

  # Documentation
  - jupyter-book <2
  - nbval
  - sphinx-autoapi

